opensbi: missing intialization
GCC 13.2.0 detects that cnt may not be initialized.
We must not assume that a local variable is 0 if we don't initialize it.

    lib/utils/reset/fdt_reset_thead.c:23:23: error:
    ‘cnt’ may be used uninitialized [-Werror=maybe-uninitialized]
    23 |         for (i = 0; i < cnt; i++) {
       |                     ~~^~~~~

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>